name: elixdev
dependencies:
    - python=3.6.2
    - nose=1.3.7
    - pandas=0.19.2
    - xlrd=1.0.0
    - pip:
        - pyparsing==2.2.0
        - toolz==0.8.2
        - git+https://github.com/jcrudy/modulecache.git
        - git+https://github.com/jcrudy/clinvoc.git